In [1]:
import pandas as pd

In [22]:
#Traitement des données avant l'execution de l'exemple
df = pd.read_csv('data.csv')
df['tax'] = df['tax'].fillna(df['tax'].mode()[0])
df['gender'] = df['gender'].fillna('inconnu')
df['country'] = df['country'].fillna('inconnu')
df['price_paid'] = (
    df['price_paid']
    .astype(str)
    .str.replace('$','', regex = False)
    .str.replace(',','', regex = False)
    .astype(float)
)

In [23]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,20.0
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,20.0
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0
...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,20.0
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,inconnu,4.59,20.0
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,20.0
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,inconnu,170.193.249.83,Canada,8.01,20.0

In [24]:
def prod_cher(i): # les fonctions sont lues de l'haut en bas
    if i < 4: # dans ce cas nous devonts mettres les valeurs plus petit toujours dans l'haut du code
        return 'pas cher'
    elif i < 7 :
        return 'cher'
    else:
        return 'très cher'

In [25]:
df['classe_prod'] = df['price_paid'].apply(prod_cher) # utilisatation de la function 'prod_cher' sur 'price_paid' avec .apply
#on crée une nouvelle colonne pour strocker le résultat

In [26]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,classe_prod
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,20.0,cher
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,20.0,très cher
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,pas cher
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,pas cher
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,très cher
...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,20.0,pas cher
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,inconnu,4.59,20.0,cher
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,très cher
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,20.0,cher
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,inconnu,170.193.249.83,Canada,8.01,20.0,très cher

In [28]:
df["groupe_prodt"] = pd.cut( #Ici nous emploions pd.cut à la place de .apply (il faut pd.cut nous contraint à créer une nouvelle colonnne))
    df["price_paid"], #nom de la colonne
    bins=[0, 4, 7, 10], #difinitions des valeurs (0, min, centre, max)
    labels=["A", "B", "C"] #les valeurs de 0 à 4  = A; 4 à 7 = B; 7 à 10 = C                          
)

In [29]:
df

,id,date,first_name,last_name,email,gender,ip_address,country,price_paid,tax,classe_prod,groupe_prodt
0,1,03/28/2021,Marylin,Alders,malders0@shop-pro.jp,Male,160.119.8.119,Canada,5.36,20.0,cher,B
1,2,03/19/2021,Hinda,Harridge,hharridge1@gnu.org,Female,210.51.172.132,Canada,8.32,20.0,très cher,C
2,3,03/17/2021,Erl,Kilminster,ekilminster2@etsy.com,Male,213.8.101.145,United States,3.73,20.0,pas cher,A
3,4,03/19/2021,Grata,Brantl,gbrantl3@umn.edu,Female,5.140.237.101,United States,3.70,20.0,pas cher,A
4,5,03/24/2021,Kanya,Beasant,kbeasant4@jigsy.com,Male,106.252.162.233,Morocco,9.24,20.0,très cher,C
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,03/24/2021,Duff,Errigo,derrigorn@elpais.com,Female,193.84.247.144,France,3.63,20.0,pas cher,A
996,997,03/17/2021,Ame,Rastall,arastallro@toplist.cz,Female,188.219.12.109,inconnu,4.59,20.0,cher,B
997,998,03/13/2021,Betty,Stickels,bstickelsrp@cloudflare.com,Male,199.80.60.87,United States,7.54,20.0,très cher,C
998,999,03/17/2021,Paquito,Tesoe,ptesoerq@rakuten.co.jp,Male,0.183.63.11,United States,5.81,20.0,cher,B
999,1000,03/23/2021,Rochelle,Pringuer,rpringuerrr@house.gov,inconnu,170.193.249.83,Canada,8.01,20.0,très cher,C