In [1]:
import pandas as pd

In [18]:
age = [10,19,20,13,11,24,25,66]
nom = ['a','b','c','d','e','f','g','h']

df = pd.DataFrame({
    'nom':nom,
    'age':age
})

In [19]:
df

  nom  age
0   a   10
1   b   19
2   c   20
3   d   13
4   e   11
5   f   24
6   g   25
7   h   66

In [20]:
def categorie_age(age):
    if age < 18:
        return "mineur"
    elif age < 60:
        return "adulte"
    else:
        return "senior"

df['status'] = df['age'].apply(categorie_age)

In [21]:
df

  nom  age  status
0   a   10  mineur
1   b   19  adulte
2   c   20  adulte
3   d   13  mineur
4   e   11  mineur
5   f   24  adulte
6   g   25  adulte
7   h   66  senior