In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('bug_dataset_50k.csv')

In [3]:
#nous cherchons ici comprendre mieux l'origine de ces valeurs Nan,
#ça nous pemettra aussi mettre en lumière les possibilités que nous avons pour les traiter
df[(df['bug_category'] == 'API Bug') & (df['error_code'].isna())] # BELLEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEeeee

,bug_id,title,description,error_code,bug_category,bug_domain,tech_stack,severity,environment,developer_role,root_cause,suggested_fix,explanation,created_at
12,BUG_000013,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,MySQL,Critical,Staging,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-12-04
59,BUG_000060,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,DevOps,Laravel,Critical,Staging,Data Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a data engineer due to its n...,2025-07-06
106,BUG_000107,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Mobile,Laravel,Critical,Development,Mobile Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a mobile developer due to it...,2025-10-04
115,BUG_000116,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,DevOps,Angular,Medium,Production,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-07-24
120,BUG_000121,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Cloud,MongoDB,Low,Development,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-11-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49674,BUG_049675,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,AWS,Critical,Production,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-07-28
49802,BUG_049803,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Data,Spring Boot,Medium,Staging,Mobile Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a mobile developer due to it...,2025-03-19
49870,BUG_049871,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,DevOps,AWS,Low,Production,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-04-29
49911,BUG_049912,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Data,MySQL,Low,Development,Security Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a security engineer due to i...,2025-02-11
49973,BUG_049974,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,Vue,Critical,Staging,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-09-17

In [4]:
df['severity'].unique()

array(['High', 'Medium', 'Critical', 'Low'], dtype=object)

In [5]:
df['error_code'].unique()

array([403., 500., 404., 503., 502., 401.,  nan, 400.])

In [6]:
api_bug = df[(df['bug_category'] == 'API Bug')]

In [7]:
API_Bug = (
    api_bug
    .groupby('error_code')
    .size()
    .sort_values(ascending = False)
)
API_Bug

error_code
503.0    405
500.0    401
400.0    398
502.0    398
403.0    390
401.0    381
404.0    377
dtype: int64

In [8]:
df.isnull().sum()

bug_id               0
title                0
description          0
error_code        6188
bug_category         0
bug_domain           0
tech_stack           0
severity             0
environment          0
developer_role       0
root_cause           0
suggested_fix        0
explanation          0
created_at           0
dtype: int64

In [9]:
code = (
    df
    .groupby('error_code')
    .size()
    .sum()
)

code + df['error_code'].isnull().sum()

np.int64(50000)

In [10]:
api_bug

,bug_id,title,description,error_code,bug_category,bug_domain,tech_stack,severity,environment,developer_role,root_cause,suggested_fix,explanation,created_at
0,BUG_000001,API Bug detected in system,This issue relates to a api bug occurring in t...,403.0,API Bug,Mobile,Spring Boot,High,Development,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-04-07
12,BUG_000013,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,MySQL,Critical,Staging,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-12-04
32,BUG_000033,API Bug detected in system,This issue relates to a api bug occurring in t...,404.0,API Bug,Web Development,Flask,Low,Staging,Mobile Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a mobile developer due to it...,2025-08-19
38,BUG_000039,API Bug detected in system,This issue relates to a api bug occurring in t...,403.0,API Bug,Backend Systems,Flask,High,Production,DevOps Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a devops engineer due to its...,2025-10-07
59,BUG_000060,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,DevOps,Laravel,Critical,Staging,Data Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a data engineer due to its n...,2025-07-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49945,BUG_049946,API Bug detected in system,This issue relates to a api bug occurring in t...,502.0,API Bug,Mobile,Kubernetes,Medium,Staging,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-09-27
49970,BUG_049971,API Bug detected in system,This issue relates to a api bug occurring in t...,400.0,API Bug,Web Development,Laravel,Critical,Staging,Frontend Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a frontend developer due to ...,2025-11-12
49973,BUG_049974,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,Vue,Critical,Staging,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-09-17
49980,BUG_049981,API Bug detected in system,This issue relates to a api bug occurring in t...,502.0,API Bug,Mobile,Docker,Critical,Production,Security Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a security engineer due to i...,2025-07-09
49992,BUG_049993,API Bug detected in system,This issue relates to a api bug occurring in t...,404.0,API Bug,Data,Spring Boot,High,Production,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-07-24

In [11]:
df[df['error_code'].isnull()]

,bug_id,title,description,error_code,bug_category,bug_domain,tech_stack,severity,environment,developer_role,root_cause,suggested_fix,explanation,created_at
12,BUG_000013,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,MySQL,Critical,Staging,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-12-04
13,BUG_000014,Performance Bug detected in system,This issue relates to a performance bug occurr...,NaN,Performance Bug,Mobile,PostgreSQL,Critical,Staging,Full-Stack Developer,Misconfiguration or logic issue related to per...,Review and fix the performance bug according t...,This bug requires a full-stack developer due t...,2025-06-30
17,BUG_000018,Deployment Bug detected in system,This issue relates to a deployment bug occurri...,NaN,Deployment Bug,Web Development,Laravel,Critical,Production,Frontend Developer,Misconfiguration or logic issue related to dep...,Review and fix the deployment bug according to...,This bug requires a frontend developer due to ...,2025-07-14
31,BUG_000032,Monitoring Bug detected in system,This issue relates to a monitoring bug occurri...,NaN,Monitoring Bug,Data,Azure,Medium,Development,Data Engineer,Misconfiguration or logic issue related to mon...,Review and fix the monitoring bug according to...,This bug requires a data engineer due to its n...,2025-08-19
42,BUG_000043,Concurrency Bug detected in system,This issue relates to a concurrency bug occurr...,NaN,Concurrency Bug,Backend Systems,AWS,Medium,Development,Data Engineer,Misconfiguration or logic issue related to con...,Review and fix the concurrency bug according t...,This bug requires a data engineer due to its n...,2025-02-27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49940,BUG_049941,Database Bug detected in system,This issue relates to a database bug occurring...,NaN,Database Bug,Backend Systems,Kubernetes,High,Production,DevOps Engineer,Misconfiguration or logic issue related to dat...,Review and fix the database bug according to b...,This bug requires a devops engineer due to its...,2025-03-11
49953,BUG_049954,Memory Leak detected in system,This issue relates to a memory leak occurring ...,NaN,Memory Leak,DevOps,MySQL,Medium,Production,Security Engineer,Misconfiguration or logic issue related to mem...,Review and fix the memory leak according to be...,This bug requires a security engineer due to i...,2025-05-18
49957,BUG_049958,Memory Leak detected in system,This issue relates to a memory leak occurring ...,NaN,Memory Leak,Cloud,Laravel,Medium,Production,Data Engineer,Misconfiguration or logic issue related to mem...,Review and fix the memory leak according to be...,This bug requires a data engineer due to its n...,2025-09-28
49969,BUG_049970,Backend Logic Bug detected in system,This issue relates to a backend logic bug occu...,NaN,Backend Logic Bug,Cloud,AWS,Critical,Staging,Mobile Developer,Misconfiguration or logic issue related to bac...,Review and fix the backend logic bug according...,This bug requires a mobile developer due to it...,2025-10-18
49973,BUG_049974,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Backend Systems,Vue,Critical,Staging,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-09-17

In [21]:
api_low = df[(df['severity'] == 'Low') & (df['bug_category'] == 'API Bug')]

In [95]:
api_low[api_low['error_code'].isnull()] # ce code me sort de l'ombre, parce qu'il me permet
#de voir les valeurs des autres colunnes des lignes où 'error_code' est null, et ça me permet de bien ajuster
#ma mask

,bug_id,title,description,error_code,bug_category,bug_domain,tech_stack,severity,environment,developer_role,root_cause,suggested_fix,explanation,created_at
120,BUG_000121,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Cloud,MongoDB,Low,Development,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-11-06
1426,BUG_001427,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Mobile,PostgreSQL,Low,Production,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-02-19
2938,BUG_002939,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,DevOps,GCP,Low,Production,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-07-09
3082,BUG_003083,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Mobile,MySQL,Low,Development,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-02-19
3307,BUG_003308,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Data,Azure,Low,Production,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48035,BUG_048036,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Web Development,Angular,Low,Staging,Frontend Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a frontend developer due to ...,2025-03-06
48571,BUG_048572,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Mobile,Vue,Low,Staging,Security Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a security engineer due to i...,2025-10-03
49326,BUG_049327,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Data,Vue,Low,Production,DevOps Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a devops engineer due to its...,2025-10-29
49870,BUG_049871,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,DevOps,AWS,Low,Production,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-04-29
49911,BUG_049912,API Bug detected in system,This issue relates to a api bug occurring in t...,NaN,API Bug,Data,MySQL,Low,Development,Security Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a security engineer due to i...,2025-02-11

In [208]:
''''mask = ((api_low['bug_domain'] == 'Cloud') &
       (api_low['tech_stack'] == 'MongoDB')&
       (api_low['environment'] == 'Development')&
       (api_low['developer_role'] == 'Mobile Developer'))'''#On va enlever le filtre sur 'developer_role'
# parce que mon avis il y a pas raison de filtre sur cette colonne, parce les erreurs peuvent survenir
#à n'importe qui. Donc dans la version ci-dessous on filtre juste sur trois colunnes ce qui permet aussi
# que notre filtre soit plus répandu
mask = (
    (api_low['bug_domain'] == 'Mobile') &
    (api_low['tech_stack'] == 'Azure')&
    (api_low['environment'] == 'Staging')
      ) # Cette mask nous retourne une ligne qui contient
#un valeur NULL dans la colunne 'error_code'
api_low[mask]

,bug_id,title,description,error_code,bug_category,bug_domain,tech_stack,severity,environment,developer_role,root_cause,suggested_fix,explanation,created_at
12839,BUG_012840,API Bug detected in system,This issue relates to a api bug occurring in t...,401.0,API Bug,Mobile,Azure,Low,Staging,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2026-01-18
14539,BUG_014540,API Bug detected in system,This issue relates to a api bug occurring in t...,404.0,API Bug,Mobile,Azure,Low,Staging,DevOps Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a devops engineer due to its...,2025-09-27
41197,BUG_041198,API Bug detected in system,This issue relates to a api bug occurring in t...,500.0,API Bug,Mobile,Azure,Low,Staging,Data Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a data engineer due to its n...,2025-11-11

In [209]:
mode_value = api_low.loc[mask, 'error_code'].mode()[0]
api_low.loc[mask & api_low['error_code'].isna(), 'error_code'] = mode_value

In [210]:
api_low['error_code'].isnull().sum()

np.int64(60)

In [211]:
a = api_low['tech_stack'].unique()

In [257]:
mask = (
    (api_low['bug_domain'] == 'Cloud') &
    (api_low['environment'] == 'Staging')
)

api_low.loc[mask, 'error_code'] = (
    api_low.loc[mask]
    .groupby('tech_stack')['error_code']
    .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else x))
)

In [270]:
error = (
    api_low
    .groupby('error_code')
    .size()
    .sort_values(ascending = False)
)
error

error_code
403    126
400    118
500    114
502    113
401    110
503    109
404    108
999      9
dtype: int64

In [266]:
api_low[api_low['error_code'] == 999]

,bug_id,title,description,error_code,bug_category,bug_domain,tech_stack,severity,environment,developer_role,root_cause,suggested_fix,explanation,created_at
120,BUG_000121,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Cloud,MongoDB,Low,Development,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-11-06
4109,BUG_004110,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Mobile,Flask,Low,Production,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-12-17
17549,BUG_017550,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Web Development,Spring Boot,Low,Development,Data Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a data engineer due to its n...,2025-03-21
22775,BUG_022776,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Backend Systems,Angular,Low,Development,Data Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a data engineer due to its n...,2025-09-09
25232,BUG_025233,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Mobile,Laravel,Low,Production,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-04-28
31999,BUG_032000,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Backend Systems,AWS,Low,Staging,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-09-03
32858,BUG_032859,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Data,Laravel,Low,Development,Full-Stack Developer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a full-stack developer due t...,2025-08-26
34203,BUG_034204,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Backend Systems,Django,Low,Production,Cloud Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a cloud engineer due to its ...,2025-10-22
44585,BUG_044586,API Bug detected in system,This issue relates to a api bug occurring in t...,999,API Bug,Mobile,Laravel,Low,Production,QA Engineer,Misconfiguration or logic issue related to api...,Review and fix the api bug according to best p...,This bug requires a qa engineer due to its nat...,2025-03-21